### ISSUE TITLE
Uses of edge_in_out_indexs_s

### ISSUE THREAD

**Issue by fallinshadow** [qiankunmu/HDHGN#1]
Could you please tell me the full name of edge_in_out_indexs_s and edge_in_out_indexs_t? i regard them as edge_in_out_indexs_source and edge_in_out_indexs_target which contain the index of node, while edge_in_out_indexs_s seems to contains the index of edge

**Comment by qiankunmu** [comment]
Yep, edge_in_out_indexs_s is the index of edge, and edge_in_out_indexs_t is the index of the node, these edges connect these nodes.
