### ISSUE TITLE
你好，请问使用c++数据集时应该如何解析处理数据

### ISSUE THREAD

**Issue by asfcczxca** [qiankunmu/HDHGN#2]

**Comment by qiankunmu** [comment]
在python中你可以使用[pycparser](https://github.com/eliben/pycparser)解析代码，得到ast根结点后访问结点的各个属性得到属性下子结点，储存对应信息并递归调用访问子结点，和我访问python与java的方法一样。不同之处在于访问属性的方法可能不一样，你可能要使用dir()并搭配筛选条件来获取包含子结点的属性。
我没有在完整的c++数据集上实现过，不确定是否有问题，因为pycparser是解析c的，c与c++存在不同。除了pycparser外还有其它生成c++ ast的包如tree-sitter，但我不确定其它包生成的ast子结点是否有不同的对应属性。希望对你有帮助。
