### ISSUE TITLE
edge_index and edge_in_out_head_tail

### ISSUE THREAD

**Issue by CaiYitao** [qiankunmu/HDHGN#3]
I have constructed a hyperedge index for example: `hyperedge_index: tensor([[5, 1, 4, 3, 2, 6, 7, 9, 8, 11, 12], [0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1]])`   the first row indicates the node indices, the second row indicates the source to target direction in each hyperedge. 
in order to use your directed hypergraph convolution, I should transform it into 
`hyperedge_index: tensor([[5, 1, 4, 3, 2, 6, 7, 9, 8, 11, 12], [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1]]) ` which should correspond to your `edge_in_out_index' right?  

and then we build an extra index indicate the source to target, `idx_source_targe: tensor([0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1])` which corresponds to your `edge_in_out_head_tail` is that correct? 0s indicate source/tail, 1s indicate target/head of each hyperedge, from 1 to 0 transion indicates another hyperedge. 

(Forgive me for writing in English, there is no Chinese typing support in my university workstation : )

**Comment by qiankunmu** [comment]
如果5、1、4、3、2、6结点是连接同一条超边的，且5、1、4是尾结点，3、2、6是头结点；7、9、8、11、12结点连接另一条超边，且7、9是尾结点，8、11、12是头结点，那么这么理解没有问题。除了以下两点要注意：
1. 我代码中的edge_in_out_indexs第一行是边序号，第二行是结点序号，所以如果你要直接使用我的HDHGConv的话，需要简单地交换一下，例如[ [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1], [5, 1, 4, 3, 2, 6, 7, 9, 8, 11, 12] ]作为edge_in_out_indexs。
2. 我代码中的edge_in_out_head_tail中0指头部head，1指尾部tail，当然头尾交换一下实际上并不影响运行，不过从理解的角度上讲我需要说明一下。

如果还有别的疑问欢迎继续提问，我可能不一定及时回复。

If nodes 5, 1, 4, 3, 2, 6 are connected to the same hyperedge, with nodes 5, 1, 4 being tail nodes, and nodes 3, 2, 6 being head nodes; nodes 7, 9, 8, 11, 12 are connected to another hyperedge, with nodes 7, 9 being tail nodes, and nodes 8, 11, 12 being head nodes, then this understanding is correct. However, there are two points to note:
1. In my code, the first row of edge_in_out_indexs represents the hyperedge index, and the second row represents the node index. Therefore, if you want to directly use my HDHGConv, you need to simply swap them. For example, [ [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1], [5, 1, 4, 3, 2, 6, 7, 9, 8, 11, 12] ] should be used as edge_in_out_indexs.
2. In my code, edge_in_out_head_tail uses 0 to indicate the head and 1 to indicate the tail. Of course, swapping the head and tail does not actually affect the operation, but for the sake of understanding, I need to clarify this.

If you have any more questions, feel free to continue asking. I may not be able to respond immediately.

**Comment by CaiYitao** [comment]
Great, got it,thank you!
Another question. so the `edge_index` in the functions of `edge_update` and `message` are the same as HypergraphConv in Pytorch Geometric,right?  for example, same as this case `hyperedge_index: tensor([[5, 1, 4, 3, 2, 6, 7, 9, 8, 11, 12], [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1]])`?  the first row indicates nodes indices, and the second row indicates hyperedge indices.

**Comment by qiankunmu** [comment]
edge_update中的edge_index是这样，即第一行是结点序号，第二行是边序号。不过message中的edge_index是反过来的，即第一行是边序号，第二行是结点序号。

In the edge_update function, edge_index is that the first row represents the node indices and the second row represents the edge indices. Conversely, in the message function, edge_index is that the first row represents the edge indices and the second row represents the node indices.

**Comment by CaiYitao** [comment]
Great, Thank you, I guess so. 

I also find that the hyperedge_j shape is different from hyperedge shape in forward function, which is some kind of magic to me, because I do not find any function that map num of hyperedges to num of nodes_edges for hyperedge features.
for example in the following 

```python
def forward(self, x, hyperedge_index, edge_in_out_head_tail, edge_attr, batch):
        # x [num_nodes, dim_size] edge_attr [num_edges, dim_size] hyperedge_index [2, num_nodeedges] edge_in_out_head_tail [num_nodeedges]
        print(f"hyperedge_index shape: {hyperedge_index.shape} edge_attr shape: {edge_attr.shape} ")
        hyperedges = self.edge_updater(hyperedge_index, x=x, edge_attr=edge_attr,
                                       edge_in_out_head_tail=edge_in_out_head_tail)
        # hyperedges [num_edges, dim_size]
        print(f"hyperedges shape after edge_updater: {hyperedges.shape}")
        edge_attr_out = self.edge_linear(edge_attr)
        # edge_attr_out [num_edges, dim_size]
        print(f"edge_attr_out shape: {edge_attr_out.shape}")
        hyperedges = hyperedges + edge_attr_out
        print(f"hyperedges shape after add edge_attr_out: {hyperedges.shape}")
        out = self.propagate(hyperedge_index.flip([0]), x=x, hyperedges=hyperedges,
                             edge_in_out_head_tail=edge_in_out_head_tail, batch=batch)
        return out

def message(self, edge_index=None, x_i=None, hyperedges_j=None, edge_in_out_head_tail=None):
        print(f"hyperedges_j shape: {hyperedges_j.shape}")
        m = self.to_head_tail_linear(hyperedges_j, edge_in_out_head_tail)
        print(f"hyperedge_j after head tail linear transofrm shape: {m.shape}")
```


and the print out:  

`edge update out shape: torch.Size([1, 1, 128])` 

`hyperedges shape after edge_updater: torch.Size([1, 128])`

`edge_attr_out shape: torch.Size([1, 128])`

`hyperedges shape after add edge_attr_out: torch.Size([1, 128])`

`hyperedges_j shape: torch.Size([5, 128])`

`hyperedge_j after head tail linear transofrm shape: torch.Size([5, 128])`

in your paper, it seems that it does not mention the process of transforming hyperedges feature of shape num of edges * dim into  num_nodesedge * dim.
in this case there are only one hyperedge connect with 5 nodes.  so in the forward function hyperedge have num_edges * dim_h  before it as hyperedge input in propagate function and magically the hyperedges_j is of shape num_nodes_edge in message function.

**Comment by qiankunmu** [comment]
这是torch_geometric框架的功劳。你可以看到我的模型继承自`MessagePassing`，它会自动帮你实现这样的操作。想了解详细细节的话，可以查阅torch_geometric的文档。

This is a feature of the torch_geometric framework. As you can see, my model inherits from `MessagePassing`, which automatically handles this operation. For more details, you can refer to the torch_geometric documentation.

**Comment by CaiYitao** [comment]
Great, thank you so much for your help!

**Comment by qiankunmu** [comment]
不客气！如果我的工作对你有帮助的话，欢迎引用它。没什么问题的话，我就关闭这个issue了。

No thanks! If my work is helpful to you, welcome to consider citing it. If there are no further problems, I will close this issue as completed.

**Comment by CaiYitao** [comment]
好的，谢谢，那是一定的！
